In [13]:
import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(4)
torch.save(x, 'x-file')

In [3]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [4]:
# 张量列表
y = torch.zeros(4)
torch.save([x, y], 'x-files')
x2, y2 = torch.load('x-files')
x2, y2

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [5]:
mydict = {'x':x, 'y':y}
torch.save(mydict,'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [14]:
# j加载和保存整个模型的参数
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)
    
    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
x = torch.rand((5, 20))
Y = net(x)

In [16]:
torch.save(net.state_dict(), 'mlp_params')

In [11]:
# 还原模型必须要实例化同样的模型结构，然后再读入参数
clone = MLP()
clone.load_state_dict(torch.load('mlp_params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [10]:
# 查看对同样的输入，输出结果是否一样
Y_clone = clone(x)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

## practice

In [17]:
net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 1))
X = torch.rand(size=(2, 4))
net(X)

tensor([[0.2882],
        [0.3983]], grad_fn=<AddmmBackward>)

In [19]:
torch.save(net[0].state_dict(), 'mlp_layer1')
torch.save(net[2].state_dict(),'mlp_layer2')

In [22]:
clonenet = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 1))
clonenet[0].load_state_dict(torch.load('mlp_layer1'))
clonenet[2].load_state_dict(torch.load('mlp_layer2'))


<All keys matched successfully>

In [23]:
y_clone = clonenet(X)
y_clone == net(X)

tensor([[True],
        [True]])